### ISSUE TITLE
requirements.txt file causes `UnexpectedCharError` exception when initialising project

### ISSUE THREAD

**Issue by jmfederico** [frostming/pdm#101]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

When initialising a new project where an existing requirements.txt with the contents as follow, an exception is raised:
```
tomlkit.exceptions.UnexpectedCharError: Unexpected character: '=' at line 1 col 5
```

Full output:

```
❯ pdm init -v
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use: python3.8
Using Python interpreter: /Users/foo/.pyenv/shims/python3.8 (3.8.2)
Project name [test]:
Project version [0.0.0]:
License(SPDX name) [MIT]:
Author name [Author Name]:
Author email [author@example.com]:
Python requires('*' to allow any) [>=3.8]:
Changes are written to pyproject.toml.
Traceback (most recent call last):
  File "/Users/foo/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 68, in __call__
    return self.main(*args, **kwargs)
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 100, in main
    raise err.with_traceback(traceback)
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 96, in main
    f(options.project, options)
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/commands/init.py", line 48, in handle
    actions.ask_for_import(project)
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/actions.py", line 481, in ask_for_import
    importable_files = list(find_importable_files(project))
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/utils.py", line 349, in find_importable_files
    if module.check_fingerprint(project, project_file.as_posix()):
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/formats/poetry.py", line 14, in check_fingerprint
    data = tomlkit.parse(fp.read())
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/tomlkit/api.py", line 51, in parse
    return Parser(string).parse()
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/tomlkit/parser.py", line 139, in parse
    item = self._parse_item()
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/tomlkit/parser.py", line 302, in _parse_item
    return self._parse_key_value(True)
  File "/Users/foo/.local/pipx/venvs/pdm/lib/python3.8/site-packages/tomlkit/parser.py", line 379, in _parse_key_value
    raise self.parse_error(UnexpectedCharError, "=")
tomlkit.exceptions.UnexpectedCharError: Unexpected character: '=' at line 1 col 5
```

## Steps to reproduce

- Create a **requirements.txt** file with following content:
    ```
    pytz==2019.3 \
        --hash=sha256:1c557d7d0e871de1f5ccd5833f60fb2550652da6be2693c1e02300743d21500d \
        --hash=sha256:b02c06db6cf09c12dd25137e563b31700d3b80fcc4ad23abb7a315f2789819be
    ```

- run `pdm init` and complete all the info.

## Environment Information

**pdm version**:

```bash
pdm info && pdm info --env
Python Interpreter: /Users/foo/.pyenv/shims/python3.8 (3.8.2)
Project Root:       /Users/foo/projects/pdm-test
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "19.4.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64",
  "python_full_version": "3.8.2",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.8",
  "sys_platform": "darwin"
}
```

**Comment by wenfey-trans-iot** [comment]
When I run `pdm add dagster-gcp`, got a similar error:
`[UnexpectedCharError]: Unexpected character: '#' at line 1 col 1`

**Comment by frostming** [comment]
Different causes, you may have a malformed pdm.lock, remove it and try again.

**Comment by wenfey-trans-iot** [comment]
well.... I just found there is a unexpeted letter in the head of the file...
Sorry ><
