### ISSUE TITLE
Encountered "[SyntaxError]: invalid constraint:" error while `pdm install`

### ISSUE THREAD

**Issue by felixlu** [frostming/pdm#120]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Init a project with the following content in `pyproject.toml`.
2. Run `pdm install`.

```
[build-system]
build-backend = ["pdm.builders.api"]
requires = ["pdm"]

[tool]
[tool.pdm]
author = "felix.lu <felix.lu@MY_COMPANY.com>"
description = ""
homepage = ""
license = "PRIVATE"
name = "atof"
python_requires = ">=3.7"
version = "0.0.0"

[tool.pdm.dependencies]
coreapi = "*"
croniter = "*"
django = '*'
django-celery-beat = "*"
django-filter = "*"
djangorestframework = "*"
djangorestframework-bulk = "*"
gevent = "*"
pendulum = "*"
pika = "*"
pymysql = "*"
python-dotenv = "*"
sentry-sdk = "*"

[tool.pdm.dev-dependencies]
django-debug-toolbar = "*"
ipython = "*"


[[tool.pdm.source]]
url = "http://pypi.MY_PRIVATE_PYPI.com/simple"
verify_ssl = false
name = "MY_PYPI"
```

## Actual behavior

```
$ pdm install -v
Lock file does not exist, trying to generate one...
⠙ Resolving dependencies	Adding requirement coreapi
⠴ Resolving dependencies	Adding requirement croniter
⠧ Resolving dependencies	Adding requirement django
⠹ Resolving dependencies	Adding requirement django-celery-beat
⠼ Resolving dependencies	Adding requirement django-filter
⠦ Resolving dependencies	Adding requirement djangorestframework
⠏ Resolving dependencies	Adding requirement djangorestframework-bulk
⠙ Resolving dependencies	Adding requirement gevent
⠙ Resolving dependencies	Adding requirement pendulum
⠦ Resolving dependencies	Adding requirement pika
⠏ Resolving dependencies	Adding requirement pymysql
⠙ Resolving dependencies	Adding requirement python-dotenv
⠸ Resolving dependencies	Adding requirement sentry-sdk
⠦ Resolving dependencies	Adding requirement django-debug-toolbar
⠏ Resolving dependencies	Adding requirement ipython
⠸ Resolving dependencies========Start resolving requirements========
	coreapi
	croniter
	django
	django-celery-beat
	django-filter
	djangorestframework
	djangorestframework-bulk
	gevent
	pendulum
	pika
	pymysql
	python-dotenv
	sentry-sdk
	django-debug-toolbar
	ipython
	Adding requirement django(from djangorestframework-bulk-0.2.1)
	Adding requirement djangorestframework(from djangorestframework-bulk-0.2.1)
	Adding requirement setuptools(from djangorestframework-bulk-0.2.1)
⠹ Resolving dependencies	New pin: djangorestframework-bulk-0.2.1
========Ending round 0========
	Adding requirement django-timezone-field<5.0,>=4.0(from django-celery-beat-2.0.0)
⠼ Resolving: djangorestframework-bulk 0.2.1	Adding requirement python-crontab>=2.3.4(from django-celery-beat-2.0.0)
⠦ Resolving: djangorestframework-bulk 0.2.1	Adding requirement celery(from django-celery-beat-2.0.0)
⠋ Resolving: djangorestframework-bulk 0.2.1	Adding requirement Django>=1.11.17(from django-celery-beat-2.0.0)
	New pin: django-celery-beat-2.0.0
========Ending round 1========
	Adding requirement django>=2.2(from django-timezone-field-4.0)
	Adding requirement pytz(from django-timezone-field-4.0)
⠦ Resolving: django-celery-beat 2.0.0	New pin: django-timezone-field-4.0
========Ending round 2========
	Adding requirement python-dateutil(from python-crontab-2.4.2)
⠇ Resolving: django-timezone-field 4.0	New pin: python-crontab-2.4.2
========Ending round 3========
	New pin: pika-1.1.0
========Ending round 4========
	Adding requirement pytz(from django-3.0.6)
	Adding requirement sqlparse>=0.2.2(from django-3.0.6)
⠋ Resolving: pika 1.1.0	Adding requirement asgiref~=3.2(from django-3.0.6)
⠸ Resolving: pika 1.1.0	New pin: django-3.0.6
========Ending round 5========
	New pin: sqlparse-0.3.1
========Ending round 6========
	New pin: asgiref-3.2.7
========Ending round 7========
	Adding requirement python-dateutil(from croniter-0.3.31)
	New pin: croniter-0.3.31
========Ending round 8========
	Adding requirement six>=1.5(from python-dateutil-2.8.1)
⠴ Resolving: croniter 0.3.31	New pin: python-dateutil-2.8.1
========Ending round 9========
	New pin: six-1.14.0
========Ending round 10========
	Adding requirement Django>=1.11(from django-filter-2.2.0)
	New pin: django-filter-2.2.0
========Ending round 11========
	New pin: pymysql-0.9.3
========Ending round 12========
	New pin: python-dotenv-0.13.0
========Ending round 13========
	Adding requirement Django>=1.11(from django-debug-toolbar-2.2)
⠦ Resolving: python-dotenv 0.13.0	Adding requirement sqlparse>=0.2.0(from django-debug-toolbar-2.2)
	New pin: django-debug-toolbar-2.2
========Ending round 14========
	Adding requirement coreschema(from coreapi-2.3.3)
⠋ ResolvAdding requirement itypes(from coreapi-2.3.3)
⠹ Resolving: django-debug-toolbar 2.2	Adding requirement requests(from coreapi-2.3.3)
⠦ Resolving: django-debug-toolbar 2.2	Adding requirement uritemplate(from coreapi-2.3.3)
	New pin: coreapi-2.3.3
========Ending round 15========
⠏ Resolving: coreapi 2.3.3	New pin: itypes-1.2.0
========Ending round 16========
	Adding requirement jinja2(from coreschema-0.0.4)
⠙ Resolving: itypes 1.2.0	New pin: coreschema-0.0.4
========Ending round 17========
	New pin: uritemplate-3.0.1
========Ending round 18========
	Adding requirement MarkupSafe>=0.23(from jinja2-2.11.2)
⠴ Resolving: uritemplate 3.0.1	New pin: jinja2-2.11.2
========Ending round 19========
	New pin: MarkupSafe-1.1.1
========Ending round 20========
	Adding requirement urllib3>=1.10.0(from sentry-sdk-0.14.4)
⠇ Resolving: MarkupSafe 1.1.1	Adding requirement certifi(from sentry-sdk-0.14.4)
⠋ Resolving: MarkupSafe 1.1.1	New pin: sentry-sdk-0.14.4
========Ending round 21========
	New pin: certifi-2020.4.5.1
========Ending round 22========
	New pin: urllib3-1.25.9
========Ending round 23========
Traceback (most recent call last):
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/metadata.py", line 732, in __init__
    self._data = json.loads(data)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/felix.lu/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/core.py", line 68, in __call__
    return self.main(*args, **kwargs)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/core.py", line 100, in main
    raise err.with_traceback(traceback)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/core.py", line 96, in main
    f(options.project, options)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/cli/commands/install.py", line 33, in handle
    actions.do_lock(project, strategy="all")
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/cli/actions.py", line 59, in do_lock
    resolver, requirements, project.environment.python_requires
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/resolver/core.py", line 146, in resolve
    result = resolver.resolve(requirements)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/resolvelib/resolvers.py", line 427, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/resolvelib/resolvers.py", line 324, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/resolvelib/resolvers.py", line 224, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/resolvelib/resolvers.py", line 215, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/resolver/providers.py", line 72, in get_dependencies
    deps, requires_python, summary = self.repository.get_dependencies(candidate)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/models/repositories.py", line 63, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/models/repositories.py", line 29, in wrapper
    result = func(self, candidate)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/models/repositories.py", line 106, in _get_dependencies_from_metadata
    deps = candidate.get_dependencies_from_metadata()
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/models/candidates.py", line 171, in get_dependencies_from_metadata
    metadata = self.get_metadata()
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/pdm/models/candidates.py", line 138, in get_metadata
    self.metadata = self.wheel.metadata
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/util.py", line 446, in __get__
    value = self.func(obj)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/wheel.py", line 234, in metadata
    result = Metadata(fileobj=wf)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/metadata.py", line 742, in __init__
    scheme=scheme)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/metadata.py", line 285, in __init__
    self.read_file(fileobj)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/metadata.py", line 383, in read_file
    self.set(field, value)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/metadata.py", line 478, in set
    if not scheme.is_valid_constraint_list(value):
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/version.py", line 713, in is_valid_constraint_list
    return self.is_valid_matcher('dummy_name (%s)' % s)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/version.py", line 703, in is_valid_matcher
    self.matcher(s)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/version.py", line 104, in __init__
    r = self.parse_requirement(s)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/version.py", line 98, in parse_requirement
    return parse_requirement(s)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/util.py", line 237, in parse_requirement
    versions, _ = get_versions(s)
  File "/Users/felix.lu/.local/pipx/venvs/pdm/lib/python3.7/site-packages/distlib/util.py", line 220, in get_versions
    raise SyntaxError('invalid constraint: %s' % ver_remaining)
SyntaxError: invalid constraint:
```

## Expected behavior

Install successfully.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        0.8.2
Python Interpreter: /Users/felix.lu/.pyenv/versions/3.7.7/bin/python (3.7.7)
Project Root:       /Users/felix.lu/Devel/atof
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "18.7.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64",
  "python_full_version": "3.7.7",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.7",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Oh, `distlib` can't parse python requires with an empty part:
```
>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*,
```
The last part of the above is empty.
