### ISSUE TITLE
pdm add: TypeError: object of type 'generator' has no len()

### ISSUE THREAD

**Issue by pbryan** [frostming/pdm#132]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
pdm init
pdm add -v pytest
```

## Actual behavior

```
pbryan@glider:~/Projects/t$ pdm add -v pytest
Adding packages to default dependencies: pytest
⠙ Resolving dependencies	Adding requirement pytest
========Start resolving requirements========
	pytest
Traceback (most recent call last):
  File "/home/pbryan/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/pbryan/.local/lib/python3.8/site-packages/pdm/core.py", line 68, in __call__
    return self.main(*args, **kwargs)
  File "/home/pbryan/.local/lib/python3.8/site-packages/pdm/core.py", line 103, in main
    raise err.with_traceback(traceback)
  File "/home/pbryan/.local/lib/python3.8/site-packages/pdm/core.py", line 99, in main
    f(options.project, options)
  File "/home/pbryan/.local/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/pbryan/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 140, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/pbryan/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 58, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/home/pbryan/.local/lib/python3.8/site-packages/pdm/resolver/core.py", line 146, in resolve
    result = resolver.resolve(requirements)
  File "/usr/share/python-wheels/resolvelib-0.3.0-py2.py3-none-any.whl/resolvelib/resolvers.py", line 413, in resolve
  File "/usr/share/python-wheels/resolvelib-0.3.0-py2.py3-none-any.whl/resolvelib/resolvers.py", line 306, in resolve
  File "/usr/share/python-wheels/resolvelib-0.3.0-py2.py3-none-any.whl/resolvelib/resolvers.py", line 198, in _get_criterion_item_preference
  File "/home/pbryan/.local/lib/python3.8/site-packages/pdm/resolver/providers.py", line 34, in get_preference
    return len(candidates)
TypeError: object of type 'generator' has no len()
```

## Expected behavior

No exception raised.

## Environment Information

```bash
PDM version:        0.8.6                   
Python Interpreter: /usr/bin/python3 (3.8.5)
Project Root:       /home/pbryan/Projects/t 
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.7.0-2-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 5.7.10-1 (2020-07-26)",
  "python_full_version": "3.8.5",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by pbryan** [comment]
Captured parameters provided to BaseProvider.get_preference:
```
get_preference(resolution=None, candidates=<generator object ReusePinProvider.find_matches at 0x7f82291dcdd0>, information=[RequirementInformation(requirement=<NamedRequirement pytest>, parent=None)])
```

**Comment by frostming** [comment]
What is the version of resolvelib in the same library root as pdm?

**Comment by pbryan** [comment]
```
Metadata-Version: 2.1
Name: resolvelib
Version: 0.4.0
Summary: Resolve abstract dependencies into concrete ones
Home-page: https://github.com/sarugaku/resolvelib
Author: Tzu-ping Chung
Author-email: uranusjr@gmail.com
License: ISC License
Keywords: dependency,resolution
Platform: UNKNOWN
Classifier: Development Status :: 3 - Alpha
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: ISC License (ISCL)
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 3
Classifier: Topic :: Software Development :: Libraries :: Python Modules
Provides-Extra: examples
Requires-Dist: html5lib ; extra == 'examples'
Requires-Dist: packaging ; extra == 'examples'
Requires-Dist: requests ; extra == 'examples'
Provides-Extra: lint
Requires-Dist: black ; extra == 'lint'
Requires-Dist: flake8 ; extra == 'lint'
Provides-Extra: release
Requires-Dist: setl ; extra == 'release'
Requires-Dist: towncrier ; extra == 'release'
Provides-Extra: test
Requires-Dist: commentjson ; extra == 'test'
Requires-Dist: packaging ; extra == 'test'
Requires-Dist: pytest ; extra == 'test'
```

**Comment by frostming** [comment]
No, it shows your resolvelib version is 0.3.0:
`/usr/share/python-wheels/resolvelib-0.3.0-py2.py3-none-any.whl/resolvelib/resolvers.py`

Update to 0.4.0 and this should work fine.

**Comment by pbryan** [comment]
Hmm, on Debian, `python3.8-venv` and `python3-pip` packages depend on `python-pip-whl`, which packages `resolvelib-0.3.0` wheel in `/usr/share/python-wheels`. I would have thought `pipx`-loaded libraries would have taken precedent, but clearly that's not the case. `/usr/share/python-wheels` isn't even in `sysconfig.get_paths()` so I'm not sure how it's getting in there.

I will investigate further. Not a bug in pdm. Thanks for the help. Closing bug.

**Comment by pbryan** [comment]
It looks like `pip_shims` is pulling in all of the system wheels, including the conflicting `resolvelib-0.3.0` wheel. Specifically, these lines in `pip_shims/models.py:795`:

```python
Command = ShimmedPathCollection("Command", ImportTypes.CLASS)
Command.set_default_args("__init__", name="PipCommand", summary="Default pip command.")
Command.add_mixin(SessionCommandMixin)
```

**Comment by frostming** [comment]
I can't see how `pip_shims` is pulling any wheels from the snippet.

**Comment by pbryan** [comment]
Code:
```python
print(f"BEFORE: {sys.path}")
Command = ShimmedPathCollection("Command", ImportTypes.CLASS)
Command.set_default_args("__init__", name="PipCommand", summary="Default pip command.")
Command.add_mixin(SessionCommandMixin)
print(f"AFTER: {sys.path}")
```

Output:
```
BEFORE: ['/home/pbryan/.local/pipx/venvs/pdm/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/pbryan/.local/pipx/venvs/pdm/lib/python3.8/site-packages', '/home/pbryan/.local/pipx/shared/lib/python3.8/site-packages']
AFTER: ['/usr/share/python-wheels/webencodings-0.5.1-py2.py3-none-any.whl', '/usr/share/python-wheels/msgpack-0.6.2-py2.py3-none-any.whl', '/usr/share/python-wheels/idna-2.9-py2.py3-none-any.whl', '/usr/share/python-wheels/colorama-0.4.3-py2.py3-none-any.whl', '/usr/share/python-wheels/distlib-0.3.0-py2.py3-none-any.whl', '/usr/share/python-wheels/setuptools-44.0.0-py2.py3-none-any.whl', '/usr/share/python-wheels/requests-2.23.0-py2.py3-none-any.whl', '/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl', '/usr/share/python-wheels/lockfile-0.12.2-py2.py3-none-any.whl', '/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl', '/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl', '/usr/share/python-wheels/resolvelib-0.3.0-py2.py3-none-any.whl', '/usr/share/python-wheels/toml-0.10.1-py2.py3-none-any.whl', '/usr/share/python-wheels/chardet-3.0.4-py2.py3-none-any.whl', '/usr/share/python-wheels/packaging-20.3-py2.py3-none-any.whl', '/usr/share/python-wheels/progress-1.5-py2.py3-none-any.whl', '/usr/share/python-wheels/six-1.15.0-py2.py3-none-any.whl', '/usr/share/python-wheels/html5lib-1.0.1-py2.py3-none-any.whl', '/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl', '/usr/share/python-wheels/urllib3-1.25.9-py2.py3-none-any.whl', '/usr/share/python-wheels/ipaddr-2.2.0-py2.py3-none-any.whl', '/usr/share/python-wheels/appdirs-1.4.4-py2.py3-none-any.whl', '/usr/share/python-wheels/pyparsing-2.4.7-py2.py3-none-any.whl', '/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl', '/usr/share/python-wheels/certifi-2020.4.5.1-py2.py3-none-any.whl', '/usr/share/python-wheels/distro-1.5.0-py2.py3-none-any.whl', '/home/pbryan/.local/pipx/venvs/pdm/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/pbryan/.local/pipx/venvs/pdm/lib/python3.8/site-packages', '/home/pbryan/.local/pipx/shared/lib/python3.8/site-packages']
```
