### ISSUE TITLE
Error: _parsed_url in slots conflicts with class variable

### ISSUE THREAD

**Issue by stevenheidel** [frostming/pdm#133]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Run `pdm init -v`

## Actual behavior

Error:
```
pdm init -v
Traceback (most recent call last):
  File "/Users/steven/.local/bin/pdm", line 5, in <module>
    from pdm.core import main
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 12, in <module>
    from pdm.cli.commands.base import BaseCommand
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/commands/base.py", line 4, in <module>
    from pdm.cli.options import Option, global_option, verbose_option
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/options.py", line 3, in <module>
    from pdm.project import Project
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/project/__init__.py", line 2, in <module>
    from pdm.project.core import Project  # noqa
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/project/core.py", line 17, in <module>
    from pdm.models.caches import CandidateInfoCache, HashCache
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/caches.py", line 77, in <module>
    class HashCache(pip_shims.SafeFileCache):
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/caches.py", line 90, in HashCache
    def get_hash(self, link: pip_shims.Link) -> str:
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pip_shims/shims.py", line 61, in __getattr__
    return locations[args[0]].shim()
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pip_shims/models.py", line 759, in shim
    result = self.traverse(top_path)
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pip_shims/models.py", line 751, in traverse
    result = shim.shim()
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pip_shims/models.py", line 599, in shim
    return self.shim_class(imported, self.name_to_import)
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pip_shims/models.py", line 544, in shim_class
    result = self._ensure_methods(result)
  File "/Users/steven/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pip_shims/models.py", line 464, in _ensure_methods
    type_ = type(classname, (provided,), new_functions)
ValueError: '_parsed_url' in __slots__ conflicts with class variable
```

## Expected behavior

Package is initialized

## Environment Information

``bash
# Paste the output of `pdm info && pdm info --env` below:

```

Same error as above

**Comment by frostming** [comment]
Already fixed in upstream project, please re install `pdm`
