### ISSUE TITLE
pdm add tgcrypto failed

### ISSUE THREAD

**Issue by nasyxx** [frostming/pdm#148]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
> pdm init
> pdm add tgcrypto
```

## Actual behavior

```
π pdm add -v tgcrypto
Adding packages to default dependencies: tgcrypto
⠙ Resolving dependencies	Adding requirement tgcrypto
⠹ Resolving dependencies========Start resolving requirements========
	tgcrypto
	New pin: tgcrypto-1.2.1
========Ending round 0========
  Finish resolving
========Resolution Result========
Stable pins:
	tgcrypto	1.2.1
✔ Resolution success
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Could not find a version that satisfies the requirement tgcrypto==1.2.1; python_version >= "3.4" and python_version < "4.0" (from versions: 0.0.1b1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.1, 1.2.0)

Some packages failed to install, retrying...
Could not find a version that satisfies the requirement tgcrypto==1.2.1; python_version >= "3.4" and python_version < "4.0" (from versions: 0.0.1b1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.1, 1.2.0)


Traceback (most recent call last):
  File "/Users/Nasy/Library/Python/3.9/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/Users/Nasy/Library/Python/3.9/lib/python/site-packages/pdm/core.py", line 71, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Nasy/Library/Python/3.9/lib/python/site-packages/pdm/core.py", line 106, in main
    raise err.with_traceback(traceback)
  File "/Users/Nasy/Library/Python/3.9/lib/python/site-packages/pdm/core.py", line 102, in main
    f(options.project, options)
  File "/Users/Nasy/Library/Python/3.9/lib/python/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/Users/Nasy/Library/Python/3.9/lib/python/site-packages/pdm/cli/actions.py", line 150, in do_add
    do_sync(
  File "/Users/Nasy/Library/Python/3.9/lib/python/site-packages/pdm/cli/actions.py", line 96, in do_sync
    handler.synchronize(clean=clean, dry_run=dry_run)
  File "/Users/Nasy/Library/Python/3.9/lib/python/site-packages/pdm/installers/synchronizers.py", line 308, in synchronize
    raise InstallationError("\n" + "\n".join(error_msg))
pdm.exceptions.InstallationError:
Installation failed: tgcrypto
```

## Expected behavior

Successfully install.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        0.9.0
Python Interpreter: /Users/Nasy/.macports/bin/python (3.9.0)
Project Root:       /Users/Nasy/temp/ttxtt
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "19.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64",
  "python_full_version": "3.9.0",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "darwin"
}
```

## Addition

I looked through the tgcrypto project, https://github.com/pyrogram/tgcrypto.

On the pypi and setup.py file, the version is 1.2.1.  However, on GitHub, it doesn't release the v1.2.1.

**Comment by frostming** [comment]
yeah, lock is succuessful but PyPI doesn't provide a wheel for Python 3.9. So the installation failure is expected.

**Comment by nasyxx** [comment]
> yeah, lock is succuessful but PyPI doesn't provide a wheel for Python 3.9. 

Well, I haven't notice that.  I thought it would at least have a tar.gz, but it didn't.
