### ISSUE TITLE
packaging.requirements.InvalidRequirement: Parse error at "':///home'": Expected stringEnd

### ISSUE THREAD

**Issue by ajinwu** [frostming/pdm#183]
-  I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
pip install pdm
pdm init
pdm add flask

## Actual behavior
step1 and step2 has not any error, then i use pdm to add a packages, that has this errors

## Expected behavior
parse error at "':///home'"

## Environment Information
os: arch  
python system version: 3.8.6
use version: 3.7.8 from pyenv
pdm install method: pip install pdm

```bash
# Paste the output of `pdm info && pdm info --env` below:
pdm info        
PDM version:        0.11.0                                              
Python Interpreter: /home/ajin/.pyenv/versions/3.7.8/bin/python3 (3.7.8)
Project Root:       /home/ajin/code/fastapi_test

pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.8",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.9.8-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000",
  "python_full_version": "3.7.8",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.7",
  "sys_platform": "linux"
}


```

**Comment by frostming** [comment]
Can you show the output of `pdm add -vvv flask` together with the content of `pyproject.toml`?

**Comment by ajinwu** [comment]
output:
$ pdm add -vvv flask
```python
Adding packages to default dependencies: flask
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.8/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/lib/python3.8/site-packages/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected stringEnd, found ':'  (at char 4), (line:1, col:5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ajin/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/core.py", line 71, in __call__
    return self.main(*args, **kwargs)
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/core.py", line 106, in main
    raise err.with_traceback(traceback)
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/core.py", line 102, in main
    f(options.project, options)
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 143, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 48, in do_lock
    provider = project.get_provider(strategy, tracked_names)
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/project/core.py", line 256, in get_provider
    preferred_pins = self.get_locked_candidates("__all__")
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/project/core.py", line 330, in get_locked_candidates
    result[self.meta.project_name.lower()] = self.make_self_candidate(True)
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/project/core.py", line 301, in make_self_candidate
    req = parse_requirement(shims.path_to_url(self.root.as_posix()), editable)
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/models/requirements.py", line 422, in parse_requirement
    r = NamedRequirement.parse(line)  # type: Requirement
  File "/home/ajin/.local/lib/python3.8/site-packages/pdm/models/requirements.py", line 332, in parse
    PackageRequirement.__init__(r, line)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3090, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.8/site-packages/packaging/requirements.py", line 100, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "':///home'": Expected stringEnd
```

pyproject.toml:
$ cat pyproject.toml
```toml
[tool]
[tool.pdm]
name = "flask_test"
version = "0.0.0"
description = ""
author = " <>"
license = "MIT"
homepage = ""
python_requires = ">=3.7"

[tool.pdm.dependencies]
flask = "<2.0.0,>=1.1.2"

[tool.pdm.dev-dependencies]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

**Comment by frostming** [comment]
The abnormal part is here:
```pytb
 File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3090, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.8/site-packages/packaging/requirements.py", line 100, in __init__
```
But PDM is importing `pkg_resources` from `pip._vendor.pkg_resources` ([look here](https://github.com/frostming/pdm/blob/eb952c9d41e3b782746a192a82b4a05325311668/pdm/models/requirements.py#L10-L11))
So the exception doesn't fall into `except RequirementParseError as e:` block.

Can you confirm is there any monkey-patching or path precedence issue?

**Comment by ajinwu** [comment]
yes, it is path error, I am install pyenv to create a  env, but pacman install methods path is not the same as GitHub/pyenv, so it is not insted my python path, thanks

**Comment by frostming** [comment]
Cool, so the issue can be closed?

**Comment by ajinwu** [comment]
yes, thanks for your help, and if anyone has same questions,this is my methods
```zsh
pyenv global system
pip uninstall pdm
pyenv global your_version
pip install pdm
```

**Comment by rmsc** [comment]
I'm experiencing this exact problem, but weirdly enough it only happens when `version` is set to something in `pyproject.toml`:

```toml
# works fine:
version = ""
# produces parse error:
version = "0.0.1"
```

The actual parse error I suspect comes from this:
```bash
$ pip freeze | grep home
pdm @ file:///home/<username>/.cache/yay/python-pdm/src/pdm-1.4.5/dist/pdm-1.4.5-py3-none-any.whl
pdm-pep517 @ file:///home/<username>/.cache/yay/python-pdm-pep517/src/pdm-pep517-0.6.1/dist/pdm_pep517-0.6.1-py3-none-any.whl
python-cfonts @ file:///home/<username>/.cache/yay/python-cfonts/src/python-cfonts-1.4.0/dist/python_cfonts-1.4.0-py2.py3-none-any.whl
```

These strings are put in `direct_url.json` files installed by `pip install`, according to PEP610. I'm not sure if system-wide packages are supposed to have these, though.

As a final note, this is a system-wide install in Archlinux, and I happen to be the AUR package maintainer for these three packages.

**Comment by frostming** [comment]
Just avoid installing PDM into global Python. I don't know what tooling you are using though, This should solve the problem

**Comment by lyz-code** [comment]
Hi, I'm having the same issue :S, can you help me?

`pdm` was installed with `curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -`.

```bash
$: pdm info && pdm info --env

PDM version:        1.12.8
Python Interpreter: ~/.venvs/airss/bin/python (3.9)
Project Root:       ~/projects/airss
Project Packages:   None
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.8",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.19.0-5-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19)",
  "python_full_version": "3.9.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}

$: pdm config
  auto_global = False
  build_isolation = True
  cache_dir = ~/.cache/pdm
  check_update = True
  feature.install_cache = True
  feature.install_cache_method = symlink
  parallel_install = True
  project_max_depth = 5
  pypi.json_api = False
  pypi.url = https://pypi.org/simple
  pypi.verify_ssl = True
  python.use_pyenv = True
  strategy.resolve_max_rounds = 10000
  strategy.save = minimum
  strategy.update = reuse
  use_venv = True
```

When running any command, for example `pdm install` I get:

```bash
$: pdm install

All packages are synced to date, nothing to do.

See /tmp/pdm-install-co9wjphz.log for detailed debug log.
[IndexError]: list index out of range
Add '-v' to see the detailed traceback
```

The content of `/tmp/pdm-install-co9wjphz.log` is:

```
Error occurs
Traceback (most recent call last):
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pip/_vendor/pyparsing/core.py", line 1134, in parse_string
    raise exc.with_traceback(None)
pip._vendor.pyparsing.exceptions.ParseException: Expected string_end, found ':'  (at char 4), (line:1, col:5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3101, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "':///home'": Expected string_end

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/requirements.py", line 472, in parse_requirement
    package_req = PackageRequirement(line)  # type: ignore
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Parse error at "':///home'": Expected string_end

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/termui.py", line 200, in logging
    yield logger
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 355, in synchronize
    self_candidate = self.environment.project.make_self_candidate(
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/project/core.py", line 420, in make_self_candidate
    req = parse_requirement(pip_shims.path_to_url(self.root.as_posix()), editable)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/requirements.py", line 477, in parse_requirement
    r = FileRequirement.create(**m.groupdict())
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/requirements.py", line 291, in create
    return super().create(**kwargs)  # type: ignore
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/requirements.py", line 160, in create
    return cls(**kwargs)
  File "<string>", line 12, in __init__
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/requirements.py", line 279, in __post_init__
    self._check_installable()
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/requirements.py", line 374, in _check_installable
    result = Setup.from_directory(self.path.absolute())
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/setup.py", line 37, in from_directory
    return _SetupReader.read_from_directory(dir)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/setup.py", line 59, in read_from_directory
    new_result = file_reader(filepath)
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/models/setup.py", line 74, in read_pyproject_toml
    version=metadata.version,
  File "~/.local/share/pdm/venv/lib/python3.9/site-packages/pdm/pep517/metadata.py", line 140, in version
    return re.findall(
IndexError: list index out of range
```

The `pdm` section of my `pyproject.toml` is:

```toml
[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
dynamic = ["version"]
authors = [
    {name = "Lyz", email = "lyz-code-security-advisories@riseup.net"},
]
license = {text = "GPL-3.0-only"}
requires-python = ">=3.7"
dependencies = [
    "repository-orm>=0.9.1",
    "tenacity>=8.0.1",
    "feedparser>=6.0.8",
]
name = "airss"
description = "Intelligent self-hosted content browser"
readme = "README.md"
classifiers=[
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Utilities",
    "Natural Language :: English",
]

[project.urls]
Issues = "https://github.com/lyz-code/airss/issues"
homepage = "https://github.com/lyz-code/airss"
documentation = "https://lyz-code.github.io/airss"

[project.scripts]
airss = "airss.entrypoints.cli:cli"

[project.optional-dependencies]

[tool.pdm]
version = {from = "src/airss/version.py"}
package-dir = "src"
source-includes = ["tests/"]

[tool.pdm.dev-dependencies]
lint = [
    "yamllint>=1.26.3",
    "flakehell>=0.9.0",
    "flake8-aaa>=0.12.0",
    "flake8-annotations>=2.7.0",
    "flake8-annotations-complexity>=0.0.6",
    "flake8-typing-imports>=1.11.0",
    "flake8-bugbear>=21.11.29",
    "flake8-debugger>=4.0.0",
    "flake8-fixme>=1.1.1",
    "flake8-markdown>=0.3.0",
    "flake8-mutable>=1.2.0",
    "flake8-pytest>=1.3",
    "flake8-pytest-style>=1.5.1",
    "flake8-simplify>=0.14.2",
    "flake8-variables-names>=0.0.4",
    "flake8-comprehensions>=3.7.0",
    "flake8-expression-complexity>=0.0.9",
    "flake8-use-fstring>=1.3",
    "flake8-eradicate>=1.2.0",
    "flake8-docstrings>=1.6.0",
    "pep8-naming>=0.12.1",
    "dlint>=0.12.0",
    "pylint>=2.12.2",
    # Remove the upper cap when https://github.com/flakehell/flakehell/issues/22
    # is resolved
    "flake8<4.0.0,>=3.9.2",
]
test = [
    "pytest>=6.2.5",
    "pytest-cov>=3.0.0",
    "pytest-xdist>=2.4.0",
    "pytest-freezegun>=0.4.2",
    "pydantic-factories>=0.5.0",
]
doc = [
    "mkdocs>=1.2.3",
    "mkdocs-git-revision-date-localized-plugin>=0.11",
    "mkdocs-htmlproofer-plugin>=0.7.0",
    "mkdocs-minify-plugin>=0.5.0",
    "mkdocs-autolinks-plugin>=0.4.0",
    "mkdocs-material>=8.0.5",
    "mkdocstrings>=0.16.2",
    "markdown-include>=0.6.0",
    "mkdocs-section-index>=0.3.2",
]
security = [
    "safety>=1.10.3",
    "bandit>=1.7.1",
]
fixers = [
    "autoimport>=0.9.1",
    "black>=21.12b0",
    "isort>=5.10.1",
    "yamlfix>=0.8.0",
]
typing = [
    "mypy>=0.910",
]
dev = [
    "pre-commit>=2.16.0",
    "twine>=3.8.0",
    "commitizen>=2.20.4",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

**Comment by frostming** [comment]
@lyz-code PDM didn't find `__version__ = ...` in the file `src/airss/version.py`, next release will make the error more obvious.

**Comment by lyz-code** [comment]
Thanks for the quick answer @frostming , weird because the content of `src/airss/version.py` is:

```python
"""Utilities to retrieve the information of the program version."""

import platform
import sys

__version__ = "0.1.0"  # Do not edit this line manually, let `make bump` do it.


def version_info() -> str:
    """Display the version of the program, python and the platform."""
    info = {
        "airss version": __version__,
        "python version": sys.version.replace("\n", " "),
        "platform": platform.platform(),
    }
    return "\n".join(f"{k + ':' :>30} {v}" for k, v in info.items())
```

**Comment by lyz-code** [comment]
Ouch! the comment made the regex fail :P

**Comment by frostming** [comment]
> Ouch! the comment made the regex fail :P

Oh what? that feels bad.
