### ISSUE TITLE
The dependency resolution exceeds the maximum loop depth of 100 - Unable to install Jupyter

### ISSUE THREAD

**Issue by jboyd79** [frostming/pdm#238]
- [x ] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

pdm add -d -v jupyter

## Actual behavior

Got the following message:
```
🔒 Lock failed
The dependency resolution exceeds the maximum loop depth of 100, there may be some circular dependencies in your project.
Traceback (most recent call last): ....
```

## Expected behavior

Install jupyter as dev dependency.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.2.0.post1             
Python Interpreter: /usr/bin/python3 (3.8.5)
Project Root:       /home/john/pdm-oscar    
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.0-64-generic",
  "platform_system": "Linux",
  "platform_version": "#72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021",
  "python_full_version": "3.8.5",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"

**Result of pdm add -d -v jupyter**

Adding packages to dev dependencies: jupyter
======== Start resolving requirements ========
	django-oscar[sorl-thumbnail]~=3.0
	scrapy~=2.4
...

** See attachment for all rounds **

======== Ending round 97 ========
Resolving: phonenumbers 8.12.16
	New pin: phonenumbers 8.12.16
======== Ending round 98 ========
Resolving: pillow 8.1.0
	New pin: pillow 8.1.0
======== Ending round 99 ========
🔒 Lock failed
The dependency resolution exceeds the maximum loop depth of 100, there may be some circular dependencies in your project.
Traceback (most recent call last):
  File "/home/john/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/john/.local/lib/python3.8/site-packages/pdm/core.py", line 73, in __call__
    return self.main(*args, **kwargs)
  File "/home/john/.local/lib/python3.8/site-packages/pdm/core.py", line 112, in main
    raise err.with_traceback(traceback)
  File "/home/john/.local/lib/python3.8/site-packages/pdm/core.py", line 108, in main
    f(options.project, options)
  File "/home/john/.local/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/john/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 163, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/john/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 68, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/home/john/.local/lib/python3.8/site-packages/pdm/resolver/core.py", line 135, in resolve
    result = resolver.resolve(requirements)
  File "/home/john/.local/lib/python3.8/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/john/.local/lib/python3.8/site-packages/resolvelib/resolvers.py", line 364, in resolve
    raise ResolutionTooDeep(max_rounds)
resolvelib.resolvers.ResolutionTooDeep: 100


**Entire output**
[command_output.txt](https://github.com/frostming/pdm/files/5881808/command_output.txt)




```

**Comment by frostming** [comment]
Please provide the content of `pyproject.toml`

**Comment by jboyd79** [comment]
Hi,

Sorry for the late reply.

See my attached pyproject.toml as requested.

```
[project]
name = "pdm-oscar"
version = "0.0.0"
description = ""
authors = [
    {name = "john", email = "jboyd79@gmail.com"},
]
dependencies = [
    "django-oscar[sorl-thumbnail]~=3.0",
]
dev-dependencies = [
    "scrapy~=2.4",
    "django-extensions~=3.1",
    "django-debug-toolbar~=3.2",
    "ipython~=7.19",
]
requires-python = ">=3.8"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[tool]
[tool.pdm]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

```

**Comment by frostming** [comment]
Thanks for the info, that is really a huge set of dependencies. I have raised the maximum rounds to 1000 and make it configurable in #239

**Comment by jboyd79** [comment]
Yay!

Just pip installed your master branch and Jupyter package installed with no errors.
Thanks very much for this application and for moving so fast on this.

Best Regards,
John.
