### ISSUE TITLE
ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by pawamoy** [frostming/pdm#248]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce and actual behavior

```console
$ pdm add -vvv fastapi
Adding packages to default dependencies: fastapi
======== Start resolving requirements ========
        fastapi
        Adding requirement fastapi
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/resolver/core.py", line 23, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'fastapi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/pip_shims.py", line 59, in get_abi_tag
    from wheel.pep425tags import get_abbr_impl, get_config_var
ModuleNotFoundError: No module named 'wheel.pep425tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 73, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 112, in main
    raise err.with_traceback(traceback)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 108, in main
    f(options.project, options)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/actions.py", line 163, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/actions.py", line 68, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/resolver/core.py", line 135, in resolve
    result = resolver.resolve(requirements)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/resolver/core.py", line 25, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/resolvelib/structs.py", line 148, in build_iter_view
    matches = list(matches)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/resolver/providers.py", line 117, in find_matches
    yield from super().find_matches(requirements)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/resolver/providers.py", line 44, in find_matches
    candidates = self.repository.find_candidates(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/repositories.py", line 102, in find_candidates
    cans = list(self._find_candidates(requirement))
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/repositories.py", line 233, in _find_candidates
    with self.environment.get_finder(sources) as finder, allow_all_wheels():
  File "/home/user/.basher-packages/pyenv/pyenv/versions/3.8.6/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/environment.py", line 265, in get_finder
    finder = get_finder(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/utils.py", line 97, in get_finder
    finder = get_package_finder(
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/pip_shims.py", line 121, in get_package_finder
    abi = get_abi_tag(python_version)
  File "/home/user/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/models/pip_shims.py", line 69, in get_abi_tag
    from wheel.bdist_wheel import get_config_var, get_flag
  File "/home/user/.local/pipx/shared/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 26, in <module>
    from .macosx_libfile import calculate_macosx_platform_tag
  File "/home/user/.local/pipx/shared/lib/python3.6/site-packages/wheel/macosx_libfile.py", line 41, in <module>
    import ctypes
  File "/home/user/.basher-packages/pyenv/pyenv/versions/3.8.6/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```

You'll notice the following exceptions being raised:

```
KeyError: 'fastapi'
ModuleNotFoundError: No module named 'wheel.pep425tags'
ModuleNotFoundError: No module named '_ctypes'
```

## Expected behavior

No errors 😄 ?

## Environment Information

```console
$ pdm info && pdm info --env
PDM version:        1.2.0.post1                                                              
Python Interpreter: /home/user/.basher-packages/pyenv/pyenv/shims/python3.6 (3.6.12)
Project Root:       /home/user/data/dev/pawamoy/pdmtest                             
{
  "implementation_name": "cpython",
  "implementation_version": "3.6.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "3.10.0-862.6.3.el7.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Jun 15 17:57:37 EDT 2018",
  "python_full_version": "3.6.12",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.6",
  "sys_platform": "linux"
}
```

It says "Python Interpreter: 3.6.12" though I *did* install pdm with Python 3.8.6 (you can see the file path in the traceback). Maybe I'm missing something here.

Thanks for the great project! I've been lurking for some time, and finally giving it a try 🙂 So promising!!

**Comment by pawamoy** [comment]
Solved, I was missing the libffi system lib: `sudo yum install libffi-devel` (https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul). 🙂
