### ISSUE TITLE
Importing from poetry does not create [project.urls] nor [project.scripts]

### ISSUE THREAD

**Issue by Yajo** [frostming/pdm#263]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

    pdm import -vf poetry ./pyproject.toml

## Actual behavior

In `pyproject.toml`, it creates these duplicate sections:

```toml

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/copier-org/copier/issues"
homepage = "https://github.com/copier-org/copier"
repository = "https://github.com/copier-org/copier"

[tool.poetry.scripts]
copier = "copier.cli:CopierApp.run"
```

These are appended to the file, although they also existed before, so they become duplicated.

## Expected behavior

A quick glimpse over PEP 621 tells me that this is what it should append instead:

```toml

[project.urls]
"Bug Tracker" = "https://github.com/copier-org/copier/issues"
homepage = "https://github.com/copier-org/copier"
repository = "https://github.com/copier-org/copier"

[project.scripts]
copier = "copier.cli:CopierApp.run"
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
Traceback (most recent call last):
  File "/var/home/yajo/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/var/home/yajo/.local/pipx/venvs/pdm/lib64/python3.9/site-packages/pdm/core.py", line 73, in __call__
    return self.main(*args, **kwargs)
  File "/var/home/yajo/.local/pipx/venvs/pdm/lib64/python3.9/site-packages/pdm/core.py", line 98, in main
    migrate_pyproject(options.project)
  File "/var/home/yajo/.local/pipx/venvs/pdm/lib64/python3.9/site-packages/pdm/cli/actions.py", line 601, in migrate_pyproject
    or not FORMATS["legacy"].check_fingerprint(project, project.pyproject_file)
  File "/var/home/yajo/.local/pipx/venvs/pdm/lib64/python3.9/site-packages/pdm/formats/legacy.py", line 26, in check_fingerprint
    and "pdm" in data["tool"]
  File "/var/home/yajo/.local/pipx/venvs/pdm/lib64/python3.9/site-packages/tomlkit/container.py", line 582, in __getitem__
    return OutOfOrderTableProxy(self, idx)
  File "/var/home/yajo/.local/pipx/venvs/pdm/lib64/python3.9/site-packages/tomlkit/container.py", line 711, in __init__
    self._internal_container.append(k, v)
  File "/var/home/yajo/.local/pipx/venvs/pdm/lib64/python3.9/site-packages/tomlkit/container.py", line 170, in append
    current.append(k, v)
  File "/var/home/yajo/.local/pipx/venvs/pdm/lib64/python3.9/site-packages/tomlkit/items.py", line 921, in append
    self._value.append(key, _item)
  File "/var/home/yajo/.local/pipx/venvs/pdm/lib64/python3.9/site-packages/tomlkit/container.py", line 176, in append
    raise KeyAlreadyPresent(key)
tomlkit.exceptions.KeyAlreadyPresent: Key "scripts" already exists.
```

**Comment by Yajo** [comment]
After renaming those sections, I can get proper pdm info:

```
➤ pdm info && pdm info --env
PDM version:        1.3.0                        
Python Interpreter: /usr/bin/python (3.9.1)      
Project Root:       /var/home/yajo/mydevel/copier
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.12-200.fc33.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Mon Feb 1 02:40:52 UTC 2021",
  "python_full_version": "3.9.1",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```
