### ISSUE TITLE
PDM fails to fetch a development version of selenium

### ISSUE THREAD

**Issue by ac130kz** [frostming/pdm#266]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
I attempted to add a development version of selenium to my project, and pdm fails to fetch it. Other failed combinations include: appended `@4.0.0b1` and `@v4.0.0b1`, `selenium @ https://github.com/SeleniumHQ/selenium@selenium-4.0.0-alpha-7`.
```
dependencies = [
    "selenium @ https://github.com/SeleniumHQ/selenium/tree/trunk/py",
]
```

## Actual behavior

Running `pdm update -v` yields:
```
======== Start resolving requirements ========
        bs4~=0.0
        selenium @ https://github.com/SeleniumHQ/selenium/tree/trunk/py
        Adding requirement bs4~=0.0
        Adding requirement selenium @ https://github.com/SeleniumHQ/selenium/tree/trunk/py
Cannot unpack file C:\Users\user\AppData\Local\Temp\pip-unpack-3kd7w0j4\py (downloaded from C:\Users\user\AppData\Local\Temp\pdm-build6c5z_ege\selenium, content-type: text/html; charset=utf-8); cannot detect archive format
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\resolver\core.py", line 23, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'selenium'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\progs\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\progs\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Roaming\Python\Python39\Scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\core.py", line 73, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\core.py", line 112, in main
    raise err.with_traceback(traceback)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\core.py", line 108, in main
    f(options.project, options)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\cli\commands\update.py", line 28, in handle
    actions.do_update(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\cli\actions.py", line 221, in do_update
    do_lock(project)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\cli\actions.py", line 69, in do_lock
    mapping, dependencies, summaries = resolve(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\resolver\core.py", line 138, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\resolvelib\resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\resolvelib\resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\resolver\core.py", line 25, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\resolvelib\resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\resolver\providers.py", line 41, in find_matches
    can.get_metadata()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\models\candidates.py", line 149, in get_metadata
    built = self.environment.build(ireq, self.hashes, allow_all_wheels)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pdm\models\environment.py", line 335, in build
    downloaded = pip_shims.unpack_url(
  File "c:\progs\python\lib\site-packages\pip\_internal\operations\prepare.py", line 240, in unpack_url
    unpack_file(file.path, location, file.content_type)
  File "c:\progs\python\lib\site-packages\pip\_internal\utils\unpacking.py", line 275, in unpack_file
    raise InstallationError(
pip._internal.exceptions.InstallationError: Cannot determine archive format of C:\Users\user\AppData\Local\Temp\pdm-build6c5z_ege\selenium
```

## Expected behavior
Fetch and install the latest development version of selenium. I think the error is due to the Python module being a subfolder in the selenium's monorepo.

## Environment Information

```bash
PDM version:        1.3.0
Python Interpreter: C:/Progs/Python/python.exe (3.9.1)
Project Root:       C:/Users/user/Desktop/project
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.1",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.18362",
  "python_full_version": "3.9.1",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "win32"
}
```

**Comment by ac130kz** [comment]
I managed to install using a local "editable" install, but I had to download the dependency manually.
```
dependencies = [
    "-e selenium-selenium-4.0.0-alpha-7/py",
]
 ```

**Comment by frostming** [comment]
Try this one:
```
pdm add -e 'git+https://github.com/SeleniumHQ/selenium.git@selenium-4.0.0-alpha-1#egg=selenium&subdirectory=py'
```
