### ISSUE TITLE
Cannot install playwright

### ISSUE THREAD

**Issue by pohlt** [frostming/pdm#269]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

The message at the end already hints at the fact that playwright seems to rely on a package operations which is not yet implemented. I just wanted to let you know.

## Steps to reproduce
```
pdm add -v playwright==1.8.0a1

Adding packages to default dependencies: playwright
======== Start resolving requirements ========
        playwright==1.8.0a1
        Adding requirement playwright==1.8.0a1
        Adding requirement greenlet==1.0.0(from playwright 1.8.0a1)
        Adding requirement pyee>=8.0.1(from playwright 1.8.0a1)
        Adding requirement typing-extensions(from playwright 1.8.0a1)
Resolving: playwright 1.8.0a1
        New pin: playwright 1.8.0a1
======== Ending round 0 ========
Resolving: pyee 8.1.0
        New pin: pyee 8.1.0
======== Ending round 1 ========
Resolving: typing-extensions 3.7.4.3
        New pin: typing-extensions 3.7.4.3
======== Ending round 2 ========
Resolving: greenlet 1.0.0
        New pin: greenlet 1.0.0
======== Ending round 3 ========
Finish resolving
======== Resolution Result ========
Stable pins:
         playwright 1.8.0a1
               pyee 8.1.0
  typing-extensions 3.7.4.3
           greenlet 1.0.0
Extracting package metadata
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

  Install playwright 1.8.0a1 failed
  Retry failed jobs
  Install playwright 1.8.0a1 failed

ERRORS:                                                                                                                                                                
add playwright failed:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tom/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 143, in install_candidate
    installer.install(can)
  File "/home/tom/.local/lib/python3.8/site-packages/pdm/installers/installers.py", line 48, in install
    self.install_wheel(candidate.wheel)
  File "/home/tom/.local/lib/python3.8/site-packages/pdm/installers/installers.py", line 54, in install_wheel
    wheel.install(paths, maker)
  File "/home/tom/.local/lib/python3.8/site-packages/distlib/wheel.py", line 549, in install
    row = records[u_arcname]
KeyError: 'playwright/driver/node'

Traceback (most recent call last):
  File "/home/tom/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/tom/.local/lib/python3.8/site-packages/pdm/core.py", line 73, in __call__
    return self.main(*args, **kwargs)
  File "/home/tom/.local/lib/python3.8/site-packages/pdm/core.py", line 112, in main
    raise err.with_traceback(traceback)
  File "/home/tom/.local/lib/python3.8/site-packages/pdm/core.py", line 108, in main
    f(options.project, options)
  File "/home/tom/.local/lib/python3.8/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/tom/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 178, in do_add
    do_sync(
  File "/home/tom/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 125, in do_sync
    handler.synchronize(clean=clean, dry_run=dry_run)
  File "/home/tom/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 328, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```
## Environment Information
```
PDM version:        1.3.1                   
Python Interpreter: /usr/bin/python3 (3.8.7)
Project Root:       /home/tom/proj/pw       
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.7",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.16-1-default",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Sat Feb 13 16:20:19 UTC 2021 (11381f3)",
  "python_full_version": "3.8.7",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
The issue lies in the upstream package `distlib`, it forces a package to have an entry in the `RECORDS` for each file in the wheel.

With a quick look, `pip` is using its homegrown installation method for wheels, so it doesn't have this issue. IMO the best solution is to report it to the package owner of `playwright` to make a correct wheel.

**Comment by pohlt** [comment]
Thanks, @frostming for looking into this issue. I opened an issue with the playwright guys. Let's see...

**Comment by pohlt** [comment]
The playwright team is looking into the issue: https://github.com/microsoft/playwright-python/issues/518

**Comment by kumaraditya303** [comment]
@pohlt A fix is on the way Microsoft/playwright-python#525

**Comment by frostming** [comment]
The upstream project has created a fix for the wheel and merged. Close this issue now.
