### ISSUE TITLE
Cannot parse filesystem dependency specification

### ISSUE THREAD

**Issue by ElijahSink** [frostming/pdm#288]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
```
pdm init
pdm add -e ../my-package
```

## Actual behavior
```
~/pdm-test ·······························································································  08:26:02 PM
❯ pdm init
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use: 3.9
0. /usr/bin/python3.9 (3.9.1)
1. /usr/bin/python3 (3.9.1)
2. /sbin/python3.9 (3.9.1)
3. /sbin/python3 (3.9.1)
4. /bin/python3.9 (3.9.1)
5. /bin/python3 (3.9.1)
Please select: [0]: 0
Using Python interpreter: /usr/bin/python3.9 (3.9.1)
Is the project a library that will be upload to PyPI?(y/n) [n]:
License(SPDX name) [MIT]:
Author name [Elijah Sink]:
Author email [theminorprofit@gmail.com]:
Python requires('*' to allow any) [>=3.9]:
Changes are written to pyproject.toml.

~/pdm-test ····························································································· 22s 08:26:31 PM
❯ pdm add -e ../my-package -v
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.9/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/lib/python3.9/site-packages/pyparsing.py", line 3250, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected W:(abcd...), found '.'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ejsink/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/core.py", line 73, in __call__
    return self.main(*args, **kwargs)
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/core.py", line 112, in main
    raise err.with_traceback(traceback)
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/core.py", line 108, in main
    f(options.project, options)
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 160, in do_add
    for r in [parse_requirement(line, True) for line in editables] + [
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 160, in <listcomp>
    for r in [parse_requirement(line, True) for line in editables] + [
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 445, in parse_requirement
    r = NamedRequirement.parse(line)  # type: Requirement
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 351, in parse
    PackageRequirement.__init__(r, line)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.9/site-packages/packaging/requirements.py", line 115, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "'../my-pa'": Expected W:(abcd...)
```

## Expected behavior

The dependency specification is parsed correctly.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info
PDM version:        1.3.4
Python Interpreter: /usr/bin/python3.9 (3.9.1)
Project Root:       /home/ejsink/pdm-test

❯ pdm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.19.128-microsoft-standard",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Tue Jun 23 12:58:10 UTC 2020",
  "python_full_version": "3.9.1",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Would you try the master branch?

**Comment by ElijahSink** [comment]
After installing via:
```
pip install git+https://github.com/frostming/pdm.git#egg=pdm

❯ pdm info
PDM version:        1.3.5.dev7+g96d0681
Python Interpreter: /usr/bin/python3.9 (3.9.1)
Project Root:       /home/ejsink/pdm-test
```
Then:
```
❯ pdm add -e ../my-package -v
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.9/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/lib/python3.9/site-packages/pyparsing.py", line 3250, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected W:(abcd...), found '.'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ejsink/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/core.py", line 75, in __call__
    return self.main(*args, **kwargs)
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/core.py", line 116, in main
    raise err.with_traceback(traceback)
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/core.py", line 112, in main
    f(options.project, options)
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 160, in do_add
    for r in [parse_requirement(line, True) for line in editables] + [
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 160, in <listcomp>
    for r in [parse_requirement(line, True) for line in editables] + [
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 445, in parse_requirement
    r = NamedRequirement.parse(line)  # type: Requirement
  File "/home/ejsink/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 351, in parse
    PackageRequirement.__init__(r, line)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.9/site-packages/packaging/requirements.py", line 115, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "'../my-pa'": Expected W:(abcd...)
```

**Comment by frostming** [comment]
It seems your distro have de-vendored pip's dependencies and those are not consistent with what PDM requires

**Comment by frostming** [comment]
I have a minor fix, can you pull the master again?

**Comment by ElijahSink** [comment]
The fix on master did not change anything, however installing via pipx got me past that parsing issue. Excellent! Now I'm getting a different error:
```
❯ pdm add -e ../my-package -v
Traceback (most recent call last):
  File "/home/ejsink/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 73, in __call__
    return self.main(*args, **kwargs)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 112, in main
    raise err.with_traceback(traceback)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 108, in main
    f(options.project, options)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 169, in do_add
    + ", ".join(str(stream.green(key, bold=True)) for key in requirements)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 169, in <genexpr>
    + ", ".join(str(stream.green(key, bold=True)) for key in requirements)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/iostream.py", line 92, in _style
    return click.style(text, *args, **kwargs)
  File "/home/ejsink/.local/pipx/venvs/pdm/lib/python3.9/site-packages/click/termui.py", line 519, in style
    return "".join(bits)
TypeError: sequence item 2: expected str instance, NoneType found
```

**Comment by frostming** [comment]
What is the content of `my-package/setup.py` or `my-package/pyproject.toml`?

**Comment by ElijahSink** [comment]
`my-package/pyproject.toml`:
```
[project]
name = "my-package"
version = "2.5.0"
description = ""
authors = [
    {name = "Elijah Sink", email = "theminorprofit@gmail.com"},
]
dependencies = [
    "aiohttp",
    "asyncpg",
    "dateparser",
    "pycryptodome",
    "pynacl",
    "selenium",
    "pyvirtualdisplay",
    "my-other-package [extra_name] @ git+ssh://git@gitlab.com/org/group/my-other-package.git@1.0.0-staging",
]
dev-dependencies = [
    "python-dotenv",
    "boto3",
    "pytest",
    "pytest-asyncio",
]
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[tool]
[tool.pdm]
[tool.pdm.scripts]
_.env_file = '.env'
test = 'pytest my_package -v'
download-test-data = "python -m my_package.test.data.Download"
generate-test-data = "python -m my_package.test.data.Generate"
publish-test-data = "python -m my_package.test.data.Publish"
unpublish-test-data = "python -m my_package.test.data.Unpublish"


[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"
```
`my-package/setup.py`
```
# STL
import os

# PIP
from setuptools import setup, find_packages

REQUIRED = [
    "aiohttp",
    "asyncpg",
    "dateparser",
    "pycryptodome",
    "pynacl",
    "selenium",
    "PyVirtualDisplay",
    "my_other_package[extra_name] @ git+ssh://git@gitlab.com/org/group/my-other-package.git@1.0.0-staging",
]
EXTRAS = {"dev": ["python-dotenv", "boto3", "pytest", "pytest-asyncio"]}

here = os.path.abspath(os.path.dirname(__file__))

# Load the package's __version__.py module as a dictionary.
about = {}
with open(
    os.path.join(here, "my_package", "__version__.py"), "r", encoding="utf-8"
) as f:
    exec(f.read(), about)

setup(
    name=about["__title__"],
    version=about["__version__"],
    description=about["__description__"],
    long_description=about["__description__"],
    long_description_content_type="text/markdown",
    author=["__author__"],
    author_email=["__author_email__"],
    python_requires=">=3.6",
    url=about["__url__"],
    packages=find_packages(),
    install_requires=REQUIRED,
    extras_require=EXTRAS,
    include_package_data=True,
    classifiers=[
        "Intended Audience :: Developers",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: Implementation :: CPython",
        "Programming Language :: Python :: Implementation :: PyPy",
    ],
)
```

If I remove both of those files from `my-package/`, I sensibly get a "not installable" error, but if _either_ of the two files are present, the same `TypeError: sequence item 2: expected str instance, NoneType found` occurs.

**Comment by frostming** [comment]
It turns out you have stored the metadata in two sources and PDM picks `setup.py` but it fails to parse it. A bugfix is landed in the master branch so that empty names won't cause errors. Also PEP 621 metadata is preferred.

**Comment by ElijahSink** [comment]
Thank you for your attention with this. Coming from pipenv, we were forced to use two sources of metadata, but from what I'm coming to understand, a `pyproject.toml` file fulfills both of those roles. Since we are not very familiar with the right way to set up the metadata for our package, is there a preferred place to discuss and ask questions? I don't want to file a new issue for every problem I run into.

**Comment by frostming** [comment]
Thank you for your support. You can go to the Github discussion space for those questions, it can be found on the index page of the repository.
