### ISSUE TITLE
Failed to install playwright

### ISSUE THREAD

**Issue by Aloxaf** [frostming/pdm#292]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
pdm add playwright
```

## Actual behavior

Add it without error

```
❯ pdm add playwright -vv
Adding packages to default dependencies: playwright
======== Start resolving requirements ========
        playwright
        Adding requirement playwright
        Adding requirement greenlet==1.0.0(from playwright 1.9.1)
        Adding requirement pyee>=8.0.1(from playwright 1.9.1)
        Adding requirement typing-extensions(from playwright 1.9.1)
Resolving: playwright 1.9.1
        New pin: playwright 1.9.1
======== Ending round 0 ========
Resolving: pyee 8.1.0
        New pin: pyee 8.1.0
======== Ending round 1 ========
Resolving: typing-extensions 3.7.4.3
        New pin: typing-extensions 3.7.4.3
======== Ending round 2 ========
Resolving: greenlet 1.0.0
        New pin: greenlet 1.0.0
======== Ending round 3 ========
Finish resolving
======== Resolution Result ========
Stable pins:
         playwright 1.9.1
               pyee 8.1.0
  typing-extensions 3.7.4.3
           greenlet 1.0.0
Extracting package metadata
🔒 Lock successful
Changes are written to pdm.lock.
Changes are written to pyproject.toml.
Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

  Install playwright 1.9.1 failed
  Retry failed jobs
  Install playwright 1.9.1 failed

ERRORS:
add playwright failed:
Traceback (most recent call last):
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 50, in submit
    future.set_result(func(*args, **kwargs))
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 146, in install_candidate
    installer.install(can)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/installers/installers.py", line 48, in install
    self.install_wheel(candidate.wheel)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/installers/installers.py", line 54, in install_wheel
    wheel.install(paths, maker)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/distlib/wheel.py", line 549, in install
    row = records[u_arcname]
KeyError: 'playwright/driver/playwright.sh'

Traceback (most recent call last):
  File "/home/aloxaf/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 76, in __call__
    return self.main(*args, **kwargs)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 131, in main
    raise err.with_traceback(traceback)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 127, in main
    f(options.project, options)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 183, in do_add
    do_sync(
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 130, in do_sync
    handler.synchronize(clean=clean, dry_run=dry_run)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/installers/synchronizers.py", line 331, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.4.0
Python Interpreter: /usr/bin/python3 (3.9.2)
Project Root:       /tmp/pdmtest
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.19-1-lily",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Sat, 27 Feb 2021 07:02:12 +0000",
  "python_full_version": "3.9.2",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Duplicate with #269 , please check the discussion in that issue.

**Comment by Aloxaf** [comment]
Oh, very sorry!
