### ISSUE TITLE
KeyError from git remote package installation

### ISSUE THREAD

**Issue by gregdan3** [frostming/pdm#294]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
- Create a repo with some name
- Prepare that repo as a python package (appears to have something to do with name?)
- Attempt to install from the remote repo

We observed this works with packages that have single word names such as just "example", and that this happen to match the project name. But for a project name such as "project-name", "project_name", etc, this error is observed.

See [this repo](https://github.com/gregdan3/pdm-name-example) for a short example of the issue. Run `pdm add git+ssh://git@github.com/gregdan3/pdm-name-example.git#egg=pdm-name-example -v` to demonstrate (this is already in `add.sh`). We observed this to occur with the package being named "example" and with "pdm-name-example" in all relevant locations, with the project being named "pdm-name-example".

## Actual behavior
A KeyError (specifying the in-repo package name, as opposed to the repo name) leading into a CalledProcessError -> BuildError 
```
gregdan3@Theros ~/g/o/pdm-name-example (master)> ./add.sh
Adding packages to default dependencies: pdm-name-example
======== Start resolving requirements ========
        pdm-name-example @ git+ssh://git@github.com/gregdan3/pdm-name-example.git
        Adding requirement pdm-name-example @ git+ssh://git@github.com/gregdan3/pdm-name-example.git
Preparing isolated env for PEP 517 build...
Requirement already satisfied: pdm-pep517 in /usr/lib/python3.9/site-packages (from -r /tmp/pdm-build-reqs-d8n107la.txt (line 1)) (0.5.7)
 - Adding setup.py
Traceback (most recent call last):
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 280, in <module>
    main()
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 204, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/usr/lib/python3.9/site-packages/pdm/pep517/api.py", line 48, in build_wheel
    return Path(builder.build(wheel_directory)).name
  File "/usr/lib/python3.9/site-packages/pdm/pep517/wheel.py", line 47, in build
    self._write_metadata(zip_file)
  File "/usr/lib/python3.9/site-packages/pdm/pep517/wheel.py", line 114, in _write_metadata
    dist_info = self.dist_info_name
  File "/usr/lib/python3.9/site-packages/pdm/pep517/wheel.py", line 104, in dist_info_name
    name = to_filename(self.meta.project_name)
  File "/usr/lib/python3.9/site-packages/pdm/pep517/metadata.py", line 245, in project_name
    return safe_name(self.name).lower()
  File "/usr/lib/python3.9/site-packages/pdm/pep517/utils.py", line 23, in safe_name
    return re.sub("[^A-Za-z0-9.]+", "-", name)
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/core.py", line 23, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'pdm-name-example'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/builders.py", line 85, in log_subprocessor
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'build_wheel', '/tmp/tmpuenxrrt6']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregdan3/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 76, in __call__
    return self.main(*args, **kwargs)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 131, in main
    raise err.with_traceback(traceback)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 127, in main
    f(options.project, options)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 174, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 69, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/core.py", line 152, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/core.py", line 25, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/structs.py", line 148, in build_iter_view
    matches = list(matches)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/providers.py", line 120, in find_matches
    yield from super().find_matches(requirements)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/providers.py", line 42, in find_matches
    can.get_metadata()
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/candidates.py", line 149, in get_metadata
    built = self.environment.build(ireq, self.hashes, allow_all_wheels)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/environment.py", line 343, in build
    ret = builder.build_wheel(output_dir)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/builders.py", line 251, in build_wheel
    filename = self._hook.build_wheel(out_dir)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pep517/wrappers.py", line 204, in build_wheel
    return self._call_hook('build_wheel', {
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pep517/wrappers.py", line 265, in _call_hook
    self._subprocess_runner(
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/builders.py", line 177, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/builders.py", line 93, in log_subprocessor
    raise BuildError(f"Call command {cmd} return non-zero status.")
pdm.exceptions.BuildError: Call command ['/usr/bin/python3', '/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'build_wheel', '/tmp/tmpuenxrrt6'] return non-zero status.
```

## Expected behavior
`pdm add` should successfully install a package at some git remote, given a properly formed installation string, regardless of the repo's name.

## Environment Information
```bash
gregdan3@Theros ~/g/o/pdm-name-example (master)> pdm info && pdm info --env
PDM version:        1.4.0
Python Interpreter: /usr/bin/python3 (3.9.2)
Project Root:       /home/gregdan3/git/open/pdm-name-example
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.11.2-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Fri, 26 Feb 2021 18:26:41 +0000",
  "python_full_version": "3.9.2",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
You can't install a repo that doesn't have a project name. And the name should be specified in `pyproject.toml` as PEP 621 says.

**Comment by gregdan3** [comment]
My bad- I've corrected that now. 

The reason I made that mistake, I realize now: I was trying to transition from using `pipenv` to `pdm`, and importing from a `Pipfile` does not include those fields. 

Here is a small example Pipfile, to demonstrate this behavior:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"

[dev-packages]

[requires]
python_version = "3.9"
```

And here is the `pyproject.toml` produced from `pdm install` in a directory with that Pipfile:
```
[project]
requires-python = ">=3.9"
dependencies = [
    "requests",
]
dev-dependencies = []

[tool]
[tool.pdm]
[[tool.pdm.source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

I matched the pyproject.toml to the one that is created from `pdm init`/ described in PEP 621 (which I committed in the same repo) and got the following different error:
```
Preparing isolated env for PEP 517 build...
Requirement already satisfied: pdm-pep517 in /usr/lib/python3.9/site-packages (from -r /tmp/pdm-build-reqs-5f6ukyui.txt (line 1)) (0.5.7)
 - Adding setup.py
 - Adding pdm_name_example-.dist-info/WHEEL
 - Adding pdm_name_example-.dist-info/METADATA
 - Adding pdm_name_example-.dist-info/RECORD
Traceback (most recent call last):
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/core.py", line 23, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'pdm-name-example'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregdan3/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 76, in __call__
    return self.main(*args, **kwargs)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 131, in main
    raise err.with_traceback(traceback)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/core.py", line 127, in main
    f(options.project, options)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/commands/add.py", line 35, in handle
    actions.do_add(
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 175, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/cli/actions.py", line 70, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/core.py", line 152, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/core.py", line 25, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/resolvelib/structs.py", line 148, in build_iter_view
    matches = list(matches)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/providers.py", line 120, in find_matches
    yield from super().find_matches(requirements)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/resolver/providers.py", line 42, in find_matches
    can.get_metadata()
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/pdm/models/candidates.py", line 169, in get_metadata
    self.wheel = Wheel(built)
  File "/home/gregdan3/.local/pipx/venvs/pdm/lib/python3.9/site-packages/distlib/wheel.py", line 173, in __init__
    raise DistlibException('Invalid name or '
distlib.DistlibException: Invalid name or filename: 'pdm_name_example--py3-none-any.whl'
```
