### ISSUE TITLE
[1.4.2] Errant requirement Parse error when `version = "..."` is non-empty

### ISSUE THREAD

**Issue by gregdan3** [frostming/pdm#313]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce
- Use the following pyproject.toml:
```toml
[project]
name = "project"
version = "1.0.0"
description = "example project"
authors = []
dependencies = []
dev-dependencies = []
requires-python = ">=3.7"
dynamic = []
license = {}

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```
- `pdm install -vv`
- See below error

## Actual behavior
Installation fails after locking succeeds, with the following error:
```
gregdan3@Theros ~/g/c/pdm_error (master)> pdm install -vv
Lock file does not exist, trying to generate one...
Using Python interpreter: /usr/bin/python (3.9.2)
======== Start resolving requirements ========
Finish resolving
======== Resolution Result ========
Stable pins:
Extracting package metadata
🔒 Lock successful
Changes are written to pdm.lock.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.9/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/lib/python3.9/site-packages/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected stringEnd, found ':'  (at char 4), (line:1, col:5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregdan3/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/core.py", line 76, in __call__
    return self.main(*args, **kwargs)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/core.py", line 131, in main
    raise err.with_traceback(traceback)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/core.py", line 127, in main
    f(options.project, options)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/cli/commands/install.py", line 39, in handle
    actions.do_sync(
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 129, in do_sync
    candidates.update(project.get_locked_candidates())
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/project/core.py", line 383, in get_locked_candidates
    result[self.meta.project_name.lower()] = self.make_self_candidate(True)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/project/core.py", line 351, in make_self_candidate
    req = parse_requirement(pip_shims.path_to_url(self.root.as_posix()), editable)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 448, in parse_requirement
    r = NamedRequirement.parse(line)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 361, in parse
    PackageRequirement.__init__(r, line)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.9/site-packages/packaging/requirements.py", line 115, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "':///home'": Expected stringEnd
```
Setting `version = ""` in the provided pyproject.toml will cause expected behavior.

## Expected behavior
`pdm` will first lock all package requirements (here there would be none), then install those dependencies into `__pypackages__` (none), regardless of the value of `version = "..."`.

## Environment Information
```bash
gregdan3@Theros ~/g/c/pdm_error (master)> pdm info && pdm info --env
PDM version:        1.4.2
Python Interpreter: /usr/bin/python (3.9.2)
Project Root:       /home/gregdan3/git/cf/pdm_error
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.11.6-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Thu, 11 Mar 2021 13:48:23 +0000",
  "python_full_version": "3.9.2",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

I also prepared the following Dockerfile, but could not reproduce the error I observed
```Dockerfile
FROM python:3.9-slim
RUN mkdir /app
WORKDIR /app
RUN python -m pip install -U pdm
COPY ./pyproject.toml ./
RUN pdm info && pdm info --env
RUN pdm install -vv
ENTRYPOINT ["pdm", "list"]
```

**Comment by gregdan3** [comment]
Just to be sure, I also tried the same in /tmp and got virtually the same error, which also went away when setting `version = ""`

```
gregdan3@Theros /tmp [1]> pdm install -vv
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/packaging/requirements.py", line 113, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.9/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/usr/lib/python3.9/site-packages/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected stringEnd, found ':'  (at char 4), (line:1, col:5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gregdan3/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/core.py", line 76, in __call__
    return self.main(*args, **kwargs)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/core.py", line 131, in main
    raise err.with_traceback(traceback)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/core.py", line 127, in main
    f(options.project, options)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/cli/commands/install.py", line 39, in handle
    actions.do_sync(
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/cli/actions.py", line 129, in do_sync
    candidates.update(project.get_locked_candidates())
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/project/core.py", line 383, in get_locked_candidates
    result[self.meta.project_name.lower()] = self.make_self_candidate(True)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/project/core.py", line 351, in make_self_candidate
    req = parse_requirement(pip_shims.path_to_url(self.root.as_posix()), editable)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 448, in parse_requirement
    r = NamedRequirement.parse(line)
  File "/home/gregdan3/.local/lib/python3.9/site-packages/pdm/models/requirements.py", line 361, in parse
    PackageRequirement.__init__(r, line)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.9/site-packages/packaging/requirements.py", line 115, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "':///tmp'": Expected stringEnd
```

**Comment by gregdan3** [comment]
This was caused by an apparently corrupt install. I reinstalled with `pipx install pdm && pipx ensurepath` and had no trouble. Looks to be the same resolution as #288.

`pdm` could benefit from preflight checking versions of dependencies, maybe? I'll leave this open for @frostming to comment.

**Comment by frostming** [comment]
It is likely because some of the dependencies located at `/usr/lib/python3.9/site-packages` are installed with an incompatible version. So installing with `pipx` fixes the problem. It is common that distros redistribute some packages, specifically in your case, `pip`, and devendor to refer to the *patched* version under `/usr/lib/python3.9/site-packages`. This is way I strongly don't recommend install pdm with `sudo pip install`.
