### ISSUE TITLE
几个报错的汇总

### ISSUE THREAD

**Issue by stacklens** [frostming/pdm#35]
环境：树梅派

## 问题一

安装 PDM 后，运行 pip3 报错

```python
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable
```

原因可能是 pdm 导致环境中有 2个重复的 pip3

运行python3 -m pip uninstall pip 卸载一个 pip3 后， pip3 恢复正常。

## 问题二

```python
$ python3 -m pdm add cowsay
Adding packages to default dependencies: cowsay
Changes are written to pyproject.toml.
  Finish resolving
✔ Resolution success
Changes are written to pdm.lock.
Installing cowsay 2.0.3...
Installing pdmDemo 0.0.0...
AttributeError: 'NoneType' object has no attribute 'group'
```

虽然报错，但是 pdm 可以正常运行 add，run 指令

## 问题三

```python
python3 -m pdm remove cowsay
Removing packages from default dependencies: cowsay
Changes are written to pyproject.toml.
  Finish resolving
✔ Resolution success
Changes are written to pdm.lock.
NonExistentKey: 'Key "package" does not exist.'
```

如果局部环境中只有一个包，并且执行 remove 将此包删除，则会导致 pdm.lock 中无 [package] 索引，因此 add remove update 指令均报错：

```python
$ python3 -m pdm list
Package Version
------- -------
cowsay  2.0.3 

此时可以正常 run ：
$ python3 -m pdm run cowsay moo
  ___
< moo >
  ===
        \
         \
           ^__^                             
           (oo)\_______                   
           (__)\       )\/\             
               ||----w |           
               ||     ||  
```

## 问题四

运行 $ python setup_dev.py 失败，报错如下：

```python
...
Successfully installed pip-20.0.2 pip-shims-0.5.0
Setup project for development...
Installing cursor 1.3.4...
HashMismatch: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 33f279a17789c04efd27a92501a0dad62bb011f8a4cdff93867c798d26508940
             Got        84e0405a5c7c8b5135e54cc7fd38e9afa999389830cb64a80e8f7814709afb97

Traceback (most recent call last):
  File "setup_dev.py", line 55, in <module>
    main()
  File "setup_dev.py", line 35, in main
    subprocess.check_call([venv_python.as_posix(), "-m", "pdm", "install", "-d"])
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['env/bin/python', '-m', 'pdm', 'install', '-d']' returned non-zero exit status 1.
```

 树梅派 pipenv 环境中出现此问题。

**Comment by frostming** [comment]
第一个问题，因为pdm 依赖高版本的pip，非常不推荐在全局安装，更新全局的pip可能导致系统问题

后面三个问题，先试下最新master版本再看看
