### ISSUE TITLE
Can't install black

### ISSUE THREAD

**Issue by frostming** [frostming/pdm#56]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```bash
$ pdm add black
```

## Actual behavior

```bash
Installing black 19.10b0...
Traceback (most recent call last):
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/bin/pdm", line 12, in <module>
    load_entry_point('pdm', 'console_scripts', 'pdm')()
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/lib/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fming/wkspace/github/pdm/pdm/cli/commands.py", line 93, in main
    raise err.with_traceback(traceback)
  File "/Users/fming/wkspace/github/pdm/pdm/cli/commands.py", line 89, in main
    super().main(*args, **kwargs)
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/lib/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/lib/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/lib/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/lib/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/lib/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/lib/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/fming/wkspace/github/pdm/pdm/cli/commands.py", line 172, in sync
    actions.do_sync(project, sections, dev, default, dry_run, clean)
  File "/Users/fming/wkspace/github/pdm/pdm/cli/actions.py", line 173, in do_sync
    handler.synchronize(clean=clean, dry_run=dry_run)
  File "/Users/fming/wkspace/github/pdm/pdm/installers.py", line 184, in synchronize
    self.install_candidates(
  File "/Users/fming/wkspace/github/pdm/pdm/installers.py", line 153, in install_candidates
    installer.install(can)
  File "/Users/fming/wkspace/github/pdm/pdm/installers.py", line 51, in install
    self.install_wheel(candidate.wheel)
  File "/Users/fming/wkspace/github/pdm/pdm/installers.py", line 61, in install_wheel
    wheel.install(paths, scripts)
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/lib/distlib/wheel.py", line 649, in install
    filenames = maker.make(script)
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/lib/distlib/scripts.py", line 400, in make
    entry = get_export_entry(specification)
  File "/Users/fming/wkspace/github/pdm/__pypackages__/3.8/lib/distlib/util.py", line 731, in get_export_entry
    raise DistlibException("Invalid specification "
distlib.DistlibException: Invalid specification 'blackd = blackd:patched_main ['d']'
```

## Expected behavior

Black is installed correctly.

## Environment Information

**pdm version**:

```bash
# Paste the output of `pdm info && pdm info --env` below:

```

**Comment by frostming** [comment]
Reported at https://bitbucket.org/pypa/distlib/pull-requests/1

**Comment by frostming** [comment]
The PR seems won't be merged in the near future. I will apply a patched version of `wheel.install()`.
Oh the logic is so coupled.
