### ISSUE TITLE
Error: No version available for nautc

### ISSUE THREAD

**Issue by nasyxx** [frostming/pdm#66]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

The nautc package is here: 

https://pypi.org/project/nautc/

https://github.com/nasyxx/nautc.git

## Steps to reproduce

```
mkdir temp && cd temp
pdm init
pdm add nautc
```

## Actual behavior

Failed to add package `nautc`.

```bash
λ pdm add -v nautc
Adding packages to default dependencies: nautc
Error: No version available for nautc.
Traceback (most recent call last):
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdm/cli/commands.py", line 205, in add
    actions.do_add(project, dev, section, sync, save, strategy, editables, packages)
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdm/cli/actions.py", line 218, in do_add
    resolved = do_lock(project, strategy, tracked_names, all_dependencies)
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdm/cli/actions.py", line 135, in do_lock
    mapping, dependencies, summaries = resolve(
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdm/resolver/__init__.py", line 119, in resolve
    state = resolver.resolve({k: reqs.values() for k, reqs in requirements.items()})
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdm/resolver/resolvers.py", line 298, in resolve
    resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdm/resolver/resolvers.py", line 237, in resolve
    self._contribute_to_criteria(name, requirement, parent=f"__{key}__")
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdm/resolver/resolvers.py", line 124, in _contribute_to_criteria
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/Users/Nasy/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pdm/resolver/resolvers.py", line 51, in from_requirement
    raise NoVersionsAvailable(requirement, parent)
pdm.exceptions.NoVersionsAvailable: No version available for nautc.
```

## Expected behavior

It should successfully add package `nautc`.

## Environment Information

**pdm version**:

```bash
# Paste the output of `pdm info && pdm info --env` below:
Python Interpreter: /Users/Nasy/.pyenv/versions/3.8.1/bin/python (3.8.1)
Project Root:       /Users/Nasy/temp/tp
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "19.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64",
  "python_full_version": "3.8.1",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.8",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Ah, pdm tries to find candidates that are compatible with all versions specified in `python_requires` in `pyproject.toml`. `nautc` requires python `>=3.6, <4.0`, so pdm thinks it supports a narrower set of python versions than the project.

It is a bug, pdm needs to ignore that `<4.0` for now.
