### ISSUE TITLE
error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by kevin386** [frostming/pdm#85]
OS环境：macOS
python版本：3.7

```
➜  backend_restx_pdm git:(release.001) ✗ pdm update -vv
⠋ Resolving blinkerCommand errored out with exit status 1:
 command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pdm-buildla663h3c/blinker/setup.py'"'"'; __file__='"'"'/var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pdm-buildla663h3c/blinker/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pip-wheel-781gfl3t
     cwd: /var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pdm-buildla663h3c/blinker/
Complete output (6 lines):
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
----------------------------------------
Failed building wheel for blinker
Traceback (most recent call last):
  File "/usr/local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pdm/core.py", line 68, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pdm/core.py", line 100, in main
    raise err.with_traceback(traceback)
  File "/usr/local/lib/python3.7/site-packages/pdm/core.py", line 96, in main
    f(options.project, options)
  File "/usr/local/lib/python3.7/site-packages/pdm/cli/commands/update.py", line 36, in handle
    packages=options.packages,
  File "/usr/local/lib/python3.7/site-packages/pdm/cli/actions.py", line 189, in do_update
    do_lock(project)
  File "/usr/local/lib/python3.7/site-packages/pdm/cli/actions.py", line 56, in do_lock
    resolver, requirements, project.environment.python_requires
  File "/usr/local/lib/python3.7/site-packages/pdm/resolver/__init__.py", line 119, in resolve
    state = resolver.resolve({k: reqs.values() for k, reqs in requirements.items()})
  File "/usr/local/lib/python3.7/site-packages/pdm/resolver/resolvers.py", line 298, in resolve
    resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.7/site-packages/pdm/resolver/resolvers.py", line 249, in resolve
    self._pin_criteria()
  File "/usr/local/lib/python3.7/site-packages/pdm/resolver/resolvers.py", line 216, in _pin_criteria
    dependencies = self._p.get_dependencies(candidate)
  File "/usr/local/lib/python3.7/site-packages/pdm/resolver/providers.py", line 48, in get_dependencies
    deps, requires_python, summary = self.repository.get_dependencies(candidate)
  File "/usr/local/lib/python3.7/site-packages/pdm/models/repositories.py", line 61, in get_dependencies
    requirements, requires_python, summary = getter(candidate)
  File "/usr/local/lib/python3.7/site-packages/pdm/models/repositories.py", line 27, in wrapper
    result = func(self, candidate)
  File "/usr/local/lib/python3.7/site-packages/pdm/models/repositories.py", line 130, in _get_dependencies_from_metadata
    deps = candidate.get_dependencies_from_metadata()
  File "/usr/local/lib/python3.7/site-packages/pdm/models/candidates.py", line 183, in get_dependencies_from_metadata
    metadata = self.get_metadata()
  File "/usr/local/lib/python3.7/site-packages/pdm/models/candidates.py", line 138, in get_metadata
    built = self.environment.build(ireq, self.hashes, allow_all_wheels)
  File "/usr/local/lib/python3.7/site-packages/pdm/models/environment.py", line 315, in build
    return builder.build(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/pdm/builders/wheel.py", line 37, in build
    return self._build_other(build_dir, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pdm/builders/wheel.py", line 56, in _build_other
    raise WheelBuildError(str(self.ireq))
pdm.exceptions.WheelBuildError: blinker==1.4 from http://mirrors.aliyun.com/pypi/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz#md5=8b3722381f83c2813c52de3016b68d33
```

**Comment by kevin386** [comment]
pyproject.toml

```
[build-system]
build-backend = ["pdm.builders.api"]
requires = ["pdm"]

[tool]
[tool.pdm]
author = ""
description = ""
homepage = ""
license = "MIT"
name = "backend_epay_restx_pdm"
python_requires = ">=3.7"
version = "0.1.0"

[tool.pdm.dependencies]
blinker = "==1.4"
boto3 = "==1.12.24"
celery = "==4.3.0"
coverage = "==5.0.4"
datadog = "==0.32.0"
fakeredis = "==1.1.0"
flask-apscheduler = "==1.11.0"
flask-cors = "==3.0.8"
flask-csv = "==1.2.0"
flask-httpauth = "==3.3.0"
flask-limiter = "==1.2.1"
flask-migrate = "==2.5.3"
flask-redis = "==0.4.0"
flask-restx = "==0.1.1"
flask-script = "==2.0.6"
flask-testing = "==0.8.0"
flask-wtf = "==0.14.3"
geoip2 = "==3.0.0"
gevent = "==1.4.0"
gunicorn = "==20.0.4"
kombu = "==4.6.3"
nose = "==1.3.7"
phonenumbers = "==8.11.5"
pillow = "==7.0.0"
pycryptodome = "==3.9.7"
pymysql = "==0.9.3"
python-logstash = "==0.4.6"
qiniu = "==7.2.7"
qrcode = "==6.1"
redis = "==3.3.11"
requests = "==2.23.0"
ujson = "==1.35"
urllib3 = "==1.25.8"
xmltodict = "==0.12.0"
yunpian-python-sdk = "==1.0.0"
sentry-sdk = {extras = ["flask"], version = "==0.11.2"}

[tool.pdm.dev-dependencies]
fabric = "*"


[[tool.pdm.source]]
name = "pypi"
url = "http://mirrors.aliyun.com/pypi/simple/"
verify_ssl = true


```

**Comment by frostming** [comment]
Your target Python interpreter should have `wheel` installed. Just install `wheel` using `pip3 install wheel`

I will see how I can solve it in PDM

**Comment by kevin386** [comment]
`$(pdm info --python) -m pip install wheel`

Done with this command, thanks!
