### ISSUE TITLE
failed to install alembic, ModuleNotFoundError: No module named 'setuptools.extern

### ISSUE THREAD

**Issue by kevin386** [frostming/pdm#86]
```
Synchronizing: ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉      71/80  00:00:04Command errored out with exit status 1:
 command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pdm-build_r7c39sw/alembic/setup.py'"'"'; __file__='"'"'/var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pdm-build_r7c39sw/alembic/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pip-wheel-m9rvp0oi
     cwd: /var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pdm-build_r7c39sw/alembic/
Complete output (5 lines):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kevin/workspace/backend_epay_restx_pdm/__pypackages__/3.7/lib/setuptools/__init__.py", line 14, in <module>
    from setuptools.extern.six import PY3, string_types
ModuleNotFoundError: No module named 'setuptools.extern'
----------------------------------------
Failed building wheel for alembic
Command errored out with exit status 1:
 command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pdm-build_r7c39sw/alembic/setup.py'"'"'; __file__='"'"'/var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pdm-build_r7c39sw/alembic/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
     cwd: /var/folders/bv/vvf44mtd4t54p5c4d424jpfh0000gn/T/pdm-build_r7c39sw/alembic
Complete output (5 lines):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kevin/workspace/backend_epay_restx_pdm/__pypackages__/3.7/lib/setuptools/__init__.py", line 14, in <module>
    from setuptools.extern.six import PY3, string_types
ModuleNotFoundError: No module named 'setuptools.extern'
----------------------------------------
Failed cleaning build dir for alembic
Retrying (1/1): ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2
```

**Comment by frostming** [comment]
That is OK, failed installations will be retried in the second progress.

We need to hide the error here.
