### ISSUE TITLE
OSError: Invalid cross-device link

### ISSUE THREAD

**Issue by Aloxaf** [frostming/pdm#95]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```
❯ pdm init -v
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use: 3.8
Using Python interpreter: /usr/bin/python3 (3.8.2)
Project name [zvm]:
Project version [0.0.0]:
License(SPDX name) [MIT]:
Author name [Aloxaf]:
Author email [aloxafx@gmail.com]:
Python requires('*' to allow any) [>=3.8]:
Traceback (most recent call last):
  File "/home/aloxaf/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 68, in __call__
    return self.main(*args, **kwargs)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 100, in main
    raise err.with_traceback(traceback)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/core.py", line 96, in main
    f(options.project, options)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/commands/init.py", line 47, in handle
    actions.do_init(project, name, version, license, author, email, python_requires)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/cli/actions.py", line 364, in do_init
    project.write_pyproject()
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/project/core.py", line 375, in write_pyproject
    f.write(tomlkit.dumps(self.pyproject))
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/aloxaf/.local/pipx/venvs/pdm/lib/python3.8/site-packages/pdm/utils.py", line 440, in atomic_open_for_write
    os.rename(name, filename)
OSError: [Errno 18] Invalid cross-device link: '/tmp/pdm-ebwgf6_o-atomic-write' -> '/home/aloxaf/Coding/shell/zvm/pyproject.toml'
```

## Actual behavior

Error

## Expected behavior

No Error

## Environment Information

**pdm version**: 0.6.2

```bash
# Paste the output of `pdm info && pdm info --env` below:
Python Interpreter: /usr/bin/python3 (3.8.2)
Project Root:       /home/aloxaf/Coding/shell/zvm
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.2",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.5.13-zen1-1-zen",
  "platform_system": "Linux",
  "platform_version": "#1 ZEN SMP PREEMPT Wed, 25 Mar 2020 16:04:45 +0000",
  "python_full_version": "3.8.2",
  "platform_python_implementaiton": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Sorry for the bug, it is addressed in 0.6.3 release.
